### ISSUE TITLE
bash_it recipe not compatible with `El Capitan`

### ISSUE THREAD

**Issue by codeword** [pivotal-sprout/sprout-base#10]
something about the `rootLess` feature in El Capitan is causing system ruby to install its Gem's executables into `/usr/local/bin` instead of `/usr/bin`.  There is a custom bash_it plugin (`bash_it/custom/ensure_usr_local_dirs_first.bash`) that is putting `/usr/local/bin` at the beginning of the path.  This won't work with other tools like rbenv because now binaries like `bundle` or `gem` will always resolve to the system one found in `/usr/local/bin` instead of the rbenv shim.

**Comment by wendorf** [comment]
This has been biting me, too. Do you have any ideas for a good fix?

**Comment by nertzy** [comment]
What if we rewrote `bash_it/custom/ensure_usr_local_dirs_first.bash` to place `/usr/local/bin` immediately in front of `/usr/bin` without putting it all the way in the front?

**Comment by aramprice** [comment]
@nertzy this could be helpful. this is also impacting `chruby` path manipulation. the symptom is non-system rubies ending up executing system-ruby bundler. the one installed at `/usr/local/bin/bundle` because of using `-n /usr/local/bin` to get around the [System Integrity Protection](https://support.apple.com/en-us/HT204899)

Finding a cohesive way forward should probably also address how we install the gems for running soloist, see https://github.com/pivotal-sprout/sprout-exemplar/issues/9#issuecomment-205931744 for more background
